version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "qs-anonymous-snapshot"
s3_bucket = ""
s3_prefix = "qs-anonymous-snapshot"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
confirm_changeset = true
image_repositories = []
